package pe.edu.unsch.entities;
// Generated 16-jul-2019 19:24:05 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private Integer idpedido;
	private Producto producto;
	private Date fecha;
	private long total;
	private String estado;

	public Pedido() {
	}

	public Pedido(Producto producto, Date fecha, long total, String estado) {
		this.producto = producto;
		this.fecha = fecha;
		this.total = total;
		this.estado = estado;
	}

	public Integer getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(Integer idpedido) {
		this.idpedido = idpedido;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
