package pe.edu.unsch.entities;
// Generated 16-jul-2019 19:24:05 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int idproducto;
	private Categoria categoria;
	private Color color;
	private Marca marca;
	private String nombre;
	private long precio;
	private int cantidad;
	private String descripcion;
	private String imagen;
	private byte caracteristica;
	private Set pedidos = new HashSet(0);

	public Producto() {
	}

	public Producto(int idproducto, Categoria categoria, Color color, Marca marca, String nombre, long precio,
			int cantidad, String descripcion, String imagen, byte caracteristica) {
		this.idproducto = idproducto;
		this.categoria = categoria;
		this.color = color;
		this.marca = marca;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.caracteristica = caracteristica;
	}

	public Producto(int idproducto, Categoria categoria, Color color, Marca marca, String nombre, long precio,
			int cantidad, String descripcion, String imagen, byte caracteristica, Set pedidos) {
		this.idproducto = idproducto;
		this.categoria = categoria;
		this.color = color;
		this.marca = marca;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.caracteristica = caracteristica;
		this.pedidos = pedidos;
	}

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public long getPrecio() {
		return this.precio;
	}

	public void setPrecio(long precio) {
		this.precio = precio;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public byte getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(byte caracteristica) {
		this.caracteristica = caracteristica;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

}
